version: '3'

services:
  ikala_server:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - DB_USER=postgres
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_NAME=postgres
      - DB_PASSWORD=pgpassword
      - STATIC_ROOT=/ann/static
    volumes:
      - static:/ann/static
    ports:
      - 5000:5000
    depends_on:
      - postgres
    restart: always
  
  postgres:
    image: postgres:latest
    environment:
      - POSTGRES_PASSWORD=pgpassword
    ports:
      - 5433:5432
    restart: always
  
  nginx:
    image: nginx:latest
    ports:
      - 80:80
    volumes:
      - static:/tmp/static
      - ./default.conf:/etc/nginx/conf.d/default.conf
      - ./uwsgi_params:/etc/nginx/uwsgi_params
    depends_on:
      - ikala_server
    restart: always

volumes:
  static: